/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Random;

/**
 *
 * @author vincze.attila
 */
public class HWLHebrewQuizPanel extends javax.swing.JPanel {

    /**
     * Creates new form HWLHebrewQuizPanel
     */
    private String solution;

    public HWLHebrewQuizPanel() {
        initComponents();
        rbQuiz1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        rbQuiz2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        rbQuiz3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        rbQuiz4.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    public HWLHebrewQuizPanel(String word, String solution, String quiz1, String quiz2,
            String quiz3, String quiz4, int random) {
        this();
        this.solution = solution;
        lblWord.setText(word);
        rbQuiz1.setText(quiz1);
        rbQuiz2.setText(quiz2);
        rbQuiz3.setText(quiz3);
        rbQuiz4.setText(quiz4);
        //Random randomGenerator = new Random();
        //randomGenerator.setSeed(new Date().getTime());
        //int random = randomGenerator.nextInt(4);
        switch (random) {
            case 0:
                rbQuiz1.setText(solution);
                break;
            case 1:
                rbQuiz2.setText(solution);
                break;
            case 2:
                rbQuiz3.setText(solution);
                break;
            case 3:
                rbQuiz4.setText(solution);
                break;
        }
    }

    public boolean isCorrect() {
        return ((rbQuiz1.isSelected() && rbQuiz1.getText().equals(solution))
                || (rbQuiz2.isSelected() && rbQuiz2.getText().equals(solution))
                || (rbQuiz3.isSelected() && rbQuiz3.getText().equals(solution))
                || (rbQuiz4.isSelected() && rbQuiz4.getText().equals(solution)));
    }

    public void showCorrect(){
        if (rbQuiz1.getText().equals(solution)){
            rbQuiz1.setForeground(rbQuiz1.isSelected() ? Color.blue : new Color(153, 0, 51) );
        } else if (rbQuiz2.getText().equals(solution)){
            rbQuiz2.setForeground(rbQuiz2.isSelected() ? Color.blue : new Color(153, 0, 51));
        } if (rbQuiz3.getText().equals(solution)){
            rbQuiz3.setForeground(rbQuiz3.isSelected() ? Color.blue : new Color(153, 0, 51));
        } if (rbQuiz4.getText().equals(solution)){
            rbQuiz4.setForeground(rbQuiz4.isSelected() ? Color.blue : new Color(153, 0, 51));
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblWord = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbQuiz1 = new javax.swing.JRadioButton();
        rbQuiz2 = new javax.swing.JRadioButton();
        rbQuiz3 = new javax.swing.JRadioButton();
        rbQuiz4 = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(210, 105));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWord.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(lblWord, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(rbQuiz1);
        rbQuiz1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbQuiz1.setText("aaa");
        rbQuiz1.setMaximumSize(new java.awt.Dimension(93, 23));
        rbQuiz1.setMinimumSize(new java.awt.Dimension(93, 23));
        rbQuiz1.setOpaque(false);
        rbQuiz1.setPreferredSize(new java.awt.Dimension(93, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(rbQuiz1, gridBagConstraints);

        buttonGroup1.add(rbQuiz2);
        rbQuiz2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbQuiz2.setText("bbb");
        rbQuiz2.setMaximumSize(new java.awt.Dimension(93, 23));
        rbQuiz2.setMinimumSize(new java.awt.Dimension(93, 23));
        rbQuiz2.setOpaque(false);
        rbQuiz2.setPreferredSize(new java.awt.Dimension(93, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(rbQuiz2, gridBagConstraints);

        buttonGroup1.add(rbQuiz3);
        rbQuiz3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbQuiz3.setText("ccc");
        rbQuiz3.setMaximumSize(new java.awt.Dimension(93, 23));
        rbQuiz3.setMinimumSize(new java.awt.Dimension(93, 23));
        rbQuiz3.setOpaque(false);
        rbQuiz3.setPreferredSize(new java.awt.Dimension(93, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(rbQuiz3, gridBagConstraints);

        buttonGroup1.add(rbQuiz4);
        rbQuiz4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbQuiz4.setText("ddd");
        rbQuiz4.setMaximumSize(new java.awt.Dimension(93, 23));
        rbQuiz4.setMinimumSize(new java.awt.Dimension(93, 23));
        rbQuiz4.setOpaque(false);
        rbQuiz4.setPreferredSize(new java.awt.Dimension(93, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(rbQuiz4, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWord;
    private javax.swing.JRadioButton rbQuiz1;
    private javax.swing.JRadioButton rbQuiz2;
    private javax.swing.JRadioButton rbQuiz3;
    private javax.swing.JRadioButton rbQuiz4;
    // End of variables declaration//GEN-END:variables
}
